name: Run Task Flow
on:
  schedule:
    - cron: "50 * * * *"

jobs:
  task_job_deezer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
       python-version: 3.9

    - name: install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

    - name: install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install

    - name: Run task
      run: |
        source $HOME/.poetry/env
        poetry run python musedashboard/main.py history2
    env:
      ACCESS_TOKEN : ${{ secrets.ACCESS_TOKEN }}
      DEEZER_ID: ${{ secrets.DEEZER_ID }}
      MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
      PREFECT_CLOUD_API: ${{ secrets.PREFECT_CLOUD_API }}
