name: Run Task Flow
on:
  schedule:
    - cron: "0 1/4 * * *"

jobs:
  task_job_deezer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - name: Install Python 3
      uses: actions/setup-python@v4
      with:
       python-version: 3.9
       cache: 'poetry'

    - name: install dependencies
      run: |
        poetry install

    - name: Run task
      run: |
        poetry run python musedashboard/main.py history2
    env:
      ACCESS_TOKEN : ${{ secrets.ACCESS_TOKEN }}
      DEEZER_ID: ${{ secrets.DEEZER_ID }}
      MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
      PREFECT_CLOUD_API: ${{ secrets.PREFECT_CLOUD_API }}
